# Generated by Django 2.2.10 on 2021-02-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
